server:
 port: 8080
 
spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:postgres_docker_db}?currentSchema=${DB_SCHEMA:hsm-doctor}
    username: ${DB_USER:sagarbarateA00335597}
    password: ${DB_PASSWORD:sagar@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update
     globally_quoted_identifiers: true
     naming:
       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
     hibernate:
       hibernate: org.hibernate.dialect.PostgreSQL95Dialect
